### ISSUE TITLE
container component doesn't keep style prop on replace

### ISSUE THREAD

**Issue by goldensunliu** [marnusw/react-css-transition-replace#11]
```jsx
      <ReactCSSTransitionReplace
        component='div'
        style={{ overflowY: 'auto' }}
        transitionName={{
          enter: PreviewEnter,
          leave: PreviewLeave
        }}
        transitionEnterTimeout={300}
        transitionLeaveTimeout={300}
      >
        { this.renderPreview() }
      </ReactCSSTransitionReplace>
```
on first render the inline style `css overflow-y: auto` is there, but on change of `{ this.renderPreview() }` the outer container's inline style is gone

**Comment by marnusw** [comment]
I've finally looked into this and found something quite strange. Any other style property is maintained as you would expect. It is only `overflowY` and `overflowX` that is not restored after `overflow: hidden` was added and removed.

You can disable this behaviour by setting the prop `overflowHidden={false}`. In that case `overflow: hidden` is never applied and the values on the `style` prop are maintained throughout.
