### ISSUE TITLE
removeClass before component exits causes visual glitches?

### ISSUE THREAD

**Issue by jdelStrother** [marnusw/react-css-transition-replace#113]
When react-css-transition-replace finishes a transition, it removes the "foo-leave" and "foo-leave-active" classes (https://github.com/marnusw/react-css-transition-replace/blob/4ecdd2ab2aeb8c157095232a1656048b32466bfd/packages/react-css-transition-replace/src/ReactCSSTransitionReplaceChild.js#L109-L110) via dom-helpers, then react removes the exiting child on next render.

This can result in the transitioned-out node getting rendered with no classes for a split second, which at least for me in React 18.2.0 means it's getting rendered at a default opacity of 1.0 and clashing with the active node.

Is there a reason to remove the classes on the node when its finished leaving? Can't we just leave the "foo-leave" / "foo-leave-active" classes in place and leave React to remove the node on next render?

**Comment by marnusw** [comment]
Thanks for reporting this @jdelStrother. What you propose seems sensible. Would you have time to see whether it makes a difference and submit a PR for this change?
