### ISSUE TITLE
react/lib/Object.assign not in react 0.15

### ISSUE THREAD

**Issue by jdart** [marnusw/react-css-transition-replace#14]
Module not found: Error: Cannot resolve module 'react/lib/Object.assign' in .../node_modules/react-css-transition-replace/lib

Apparently the react team suggests using lodash/underscore for utility functions now.

**Comment by marnusw** [comment]
Thanks for pointing this out @jdart. Would you mind providing a link to the source of the React team's recommendation? I would like to include the reference in the change log when I add the lodash dependency.

**Comment by jdart** [comment]
I think this is the main discussion: https://github.com/facebook/react/pull/6376

Apparently you could use the spread operator instead of Object.assign. React is now using the npm package object-assign.

**Comment by jdart** [comment]
There's a nice workaround here from @pascalpp https://github.com/react-ga/react-ga/issues/53

**Comment by marnusw** [comment]
It looks like React is including the `object-assign` lib now so I've opted to do the same here. The change is available in `v1.1.2`.
