### ISSUE TITLE
Not compatible with React 15.0.1

### ISSUE THREAD

**Issue by ajzozakiewicz** [marnusw/react-css-transition-replace#15]
Any plans on fixing this in the near future? Had to rollback in order to accommodate this module.

**Comment by marnusw** [comment]
Yes, I certainly still consider the module under active development. You'll have to give me a few days though. I haven't quite had the time to keep up with the React 15 developments these past weeks, but it seems it should be a priority now.

**Comment by marnusw** [comment]
@ajzozakiewicz I've updated to React `15.0.1` and I didn't find any problems. I've also looked through the change log and couldn't really find anything that would indicate incompatibility. Would you mind giving me some additional info? 

(Or were you just referring to the peer dependency config?)

**Comment by liquidox** [comment]
I have that peer dependency issue indeed:

npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-dom@15.0.1 does not satisfy its siblings'
 peerDependencies requirements!
npm ERR! peerinvalid Peer react-dropdown@1.0.3 wants react-dom@^0.14.7 || ^15.0.
0-0
npm ERR! peerinvalid Peer velocity-react@1.1.5 wants react-dom@^0.14.0 || ^15.0.
0
npm ERR! peerinvalid Peer react-css-transition-replace@1.1.2 wants react-dom@^0.
14.0

How do I resolve this?

**Comment by marnusw** [comment]
For the time being I have released `v1.2.0-beta` which allows `react@15.0.1` as a peer dependency. 

I noticed that when content is added/removed completely in rapid succession weird things happen. I imagine this is due to React using fewer `spans` in the markup, but I have yet to investigate this. I will resolve this issue before releasing a new stable version.

**Comment by ajzozakiewicz** [comment]
Upgrading to npm 3.8 + now makes peer dependencies warnings so I am now able to build.

Peer dependency was my only issue. Sorry I was not aware I was not on the latest version of npm.

Thanks

AJ
