### ISSUE TITLE
Rendering table rows

### ISSUE THREAD

**Issue by jmatsushita** [marnusw/react-css-transition-replace#19]
Would be nice to implement this: https://facebook.github.io/react/docs/animation.html#rendering-a-different-component

I'm stuck rendering a `<tr>` in a `<table>` since it gets wrapped into a `<span>`.

**Comment by jmatsushita** [comment]
Ha. It's implemented. So the problem is that the `onlyChild` constraint doesn't work because of the multiple `<td>`s in each row.

**Comment by jmatsushita** [comment]
Ha. Wrapping `<tr>`s  in `<tbody>` is valid. So `<ReactCSSTransitionReplace component="tbody">` with `<tr>` as the `onlyChild` works.

**Comment by marnusw** [comment]
I'm glad you found a solution @jmatsushita.
