### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by adjohu** [marnusw/react-css-transition-replace#2]
Due to the module being es6 - could you maybe create a dist which is compiled?

**Comment by marnusw** [comment]
@adjohu, the latest version should contain a `lib` folder with ES5 files. The original ES6 files are in `src`.

**Comment by adjohu** [comment]
still on release 0.1.3?

**Comment by adjohu** [comment]
Ok - I'm up to date, but it's still using Object.assign rather than _extends in the compiled code and therefore still erroring.

**Comment by marnusw** [comment]
@adjohu, it seems this was a caveat of Babel that I wasn't aware of. I'm importing the `object.assign` function from the React library now in v0.1.4 which seems to be working. Let me know if there are any further problems.
