### ISSUE TITLE
Support CommonJS

### ISSUE THREAD

**Issue by skovhus** [marnusw/react-css-transition-replace#22]
Small thing that caught my eye when upgrading from a 0.x version to 1.x. : )

Currently `react-css-transition-replace` is not compatible with CommonJS. So you need to remember to add `.default` when importing it. 

```const ReactCSSTransitionReplace = require('react-css-transition-replace').default;```

Although most people are using ES2015 these days, I think it would be nice to be compatible with CommonJS or at least document the lack of support.

Thanks 👍

**Comment by le0nik** [comment]
Added support for commonjs in my fork: https://github.com/le0nik/react-css-transition-replace-plus

**Comment by marnusw** [comment]
The support added by @le0nik has been incorporated in `v2.0.0`.
