### ISSUE TITLE
Unable to get property 'children' of undefined or null reference 

### ISSUE THREAD

**Issue by mderrick** [marnusw/react-css-transition-replace#23]
On IE10 I get:

`Unable to get property 'children' of undefined or null reference`

This is also replicable on your [demo page](https://marnusw.github.io/react-css-transition-replace/). What browser support is expected?

Thanks :)

**Comment by mderrick** [comment]
**Update:** I pulled your repository and ran it locally and it worked just fine on IE10. I noticed that the `lib` directory that is published on npm has a [different output](https://www.diffchecker.com/q5QqMwv8) than that of the one I ran locally. Both the npm package installed and the repository I ran locally are on 1.3.0 but the published one does not work on IE10.

Hope this helps a little.

**Comment by le0nik** [comment]
Added support for IE<=11 in my fork: https://github.com/le0nik/react-css-transition-replace-plus

**Comment by marnusw** [comment]
The support added by @le0nik has been incorporated in `v2.0.0`.
