### ISSUE TITLE
Component refresh after finishing transition

### ISSUE THREAD

**Issue by Enitoni** [marnusw/react-css-transition-replace#24]
I'm using your crossfade example with react-router:

```
<ReactCSSTransitionReplace transitionName="cross-fade" transitionAppear={true} transitionAppearTimeout={1000} transitionEnterTimeout={1000} transitionLeaveTimeout={1000}>
  {React.cloneElement(this.props.children, { key: this.props.location.pathname,})}
</ReactCSSTransitionReplace>
```

But as soon as the fade finishes, the component being routed to is refreshed and all the animations within the component (if any) refresh as well.

Edit: It seems according to dev tools that it inserts a new version of the component after the animation finishes. Any way around this?

**Comment by le0nik** [comment]
Stumbled upon this a while ago and fixed it in my fork: https://github.com/le0nik/react-css-transition-replace-plus

**Comment by marnusw** [comment]
The support added by @le0nik has been incorporated in `v2.0.0`.
