### ISSUE TITLE
Transition not working with nuka-carousel

### ISSUE THREAD

**Issue by jonas-arkulpa** [marnusw/react-css-transition-replace#26]
Hey @marnusw,

Thanks for your awesome package.
I successfully implemented your project to display transitions between page changes of a wizard.
But as soon as the next page contains a [nuka-carousel](https://github.com/FormidableLabs/nuka-carousel) the transition isn't working correctly. To be more specific, the next page is displayed instantly before the transition of the first one has ende. This way the content overlaps.
Do you have any idea what could cause this misbehaviour?
Just let me know if you need more details.

**Comment by marnusw** [comment]
I think I read at some point in the past (or had the experience) that nested animations don't play very well together. Is the carousel animating on mount? If that is the case the problem could be due to that mount animation clashing with this component's enter animation. 

Just an initial thought, I'll have to think about it and look into that carousel before I could really say, I might be completely wrong. If you do some searching on whether the above might indeed cause problems and/or try disabling any on mount animations in the carousel that might provide insight sooner.

**Comment by jonas-arkulpa** [comment]
Thanks for your initial thought. I tried to narrow down the cause of the issue, but haven't been successful till yet. I don't have enough experience debugging animations.
I would be very glad if you can help me with this problem.

**Comment by jonas-arkulpa** [comment]
@marnusw Is there any update about this issue?

**Comment by marnusw** [comment]
@jonas-arkulpa would you give the `next` branch a try and see if that works better? I don't believe it's quite ready for release yet, but if it works for you it can be pulled from GitHub for the time being. I will include the lib folder on the `next` branch to this end shortly.

**Comment by jonas-arkulpa** [comment]
@marnusw I tried your next branch with some helpful results.
At first the animation failed on every page. Even on those without a nuka-carusel.
On each of these pages are input fields.
I was able to identify the autofocus as the cause of the problem, as soon as I disabled the autofocus the animations worked.
The nuka-carusel, however, does not contain any mention of an autofocus in its source.

**Comment by marnusw** [comment]
Thanks for the update @jonas-arkulpa. It is interesting that autofocus on inputs used to work but stopped with this update, I wouldn't have expected that. I think this library will move in this direction, so for the time being please fix your dependency to the current version. 

Once the these changes have been merged the implementation will match that of `react-css-transition-group` quite closely and then we can look at these specific cases in more detail. First perhaps input autofocus and then nuka-carousel.

**Comment by jonas-arkulpa** [comment]
I have to note that I didn't use autofocus on these inputs at the time I reported the issue.
So I'm not sure if it stopped working with this update.

Currently I do not use your library in production, so it isn't a problem to wait for a new release.
Just ping me if you need more information or help with the investigation of the issue.

**Comment by jonas-arkulpa** [comment]
I close the issue as I do not need a fix anymore and it is really an edge case.
