### ISSUE TITLE
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs.

### ISSUE THREAD

**Issue by zabojad** [marnusw/react-css-transition-replace#3]
I'm running into this issue when trying to use react-css-transition-replace:
```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```
I thought it is because the npm version uses 0.14.0-rc1 but even when using the master version that uses 0.14.0, I get this...

Any idea what I'm doing wrong ?

**Comment by marnusw** [comment]
I've come across this error when I have a local `npm` dependency which depends on React linked into my project with `npm link`. When running `npm link` in the dependency folder all its dependencies, including `react`, gets installed. When you import this dependency in your project, it references its own locally installed `react`, while the project uses its own instance. 

The result is that, as the error message you posted states, you have multiple copies of React loaded which breaks.

I don't know if there is a solution for this problem. I have resolved to accept the rule that dependencies that depend on React themselves can't be linked with `npm link`.

If you're not doing something like this we can investigate further.

I just released v0.2.1 which uses `react@v0.14.0` and not the release candidate.

**Comment by zabojad** [comment]
Actually, I do not npm link at all. But I do use React without the npm package. I mean, I explicitely import React in my HTML page header withing scripts tags:
```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.0/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.0/react-dom.js"></script>
```
Is there a way to use your component without using npm packages ?

**Comment by marnusw** [comment]
No, unfortunately not at the moment. I've seen other repos that support both CommonJS and script tags (and RequireJS). It should boil down to checking if you're in a CommonJS environment or not and acting accordingly, although I can't recall the specifics right now. 

If you'd be willing to create a PR I will merge it. I can also take a look when I have some time, but I can't make promises on that right now.

**Comment by zabojad** [comment]
If I install your component with the last npm package you've released, I get this:
```
sudo npm install react-css-transition-replace
Password:
npm WARN package.json react-addons-transition-group@0.14.0 No repository field.
npm WARN package.json react-addons-pure-render-mixin@0.14.0 No repository field.
npm WARN package.json react-addons-update@0.14.0 No repository field.
npm WARN package.json react-addons-create-fragment@0.14.0 No repository field.
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "react-css-transition-replace"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-css-transition-replace does not satisfy its siblings' peerDependencies requirements!
```

And I've just material-ui installed too...

**Comment by marnusw** [comment]
I did an `npm update` on one of my own projects earlier this evening and everything installed fine. But tomorrow I'll create a new project and include react 0.14, material-ui 0.13 and this latest release just to make sure it works.

What I find strange though is that those packages your install complained about aren't used by this lib at all...

**Comment by zabojad** [comment]
sorry @marnusw it was an issue at my side... For me you can close this ticket or let it open until I or someone else package this component to work without require() calls...
