### ISSUE TITLE
scrollTop gets set to 0 on the leaving component before the animation starts, causing a visual jump

### ISSUE THREAD

**Issue by Tawpie** [marnusw/react-css-transition-replace#30]
Steps to reproduce:
-- scrollable component, scrolled somewhere "not at the top"
-- any other component
-- place the scrollable component in a reactCSSTransitionReplace component
-- swap out the scrollable component.

Expected:
-- the 'old' scrollable component just animates

Actual:
-- the 'old' scrollable component jumps to scrollTop=0 and then the animation begins

Is there a way to leave the old scrollable component "where it is"?

**Comment by marnusw** [comment]
Thanks for pointing this out @Tawpie, it's not a use case I had considered before. I suspect the component will lose its scroll position whenever it gets remounted unless it is maintained explicitly. If remounting can't be avoided perhaps life cycle methods could be used to store the scroll position and maintain it. I haven't given any thought to details though. I don't have much time at the moment, but I would like to look into this at some point. Would you be willing to create a PR adding an example of your use case to the demo included in the repo? That would make it easier to reproduce and test in the future.

**Comment by marnusw** [comment]
I honestly haven't had time to reproduce/investigate this issue specifically, but I'd be interested to know whether the rewrite on the `next` branch works better for you.

**Comment by mlp73** [comment]
+1 exact same issue here.
The overflow auto to overflow hidden is making a jump.

**Comment by Tawpie** [comment]
@Marnus I may not be able to be of much help—I had to move on. If I have some space cycles, I’ll look into it further!

**Comment by marnusw** [comment]
If this happens in version 3 and is still an issue it can be reopened.
