### ISSUE TITLE
Breaks since 15.4.0 was released

### ISSUE THREAD

**Issue by seriallos** [marnusw/react-css-transition-replace#32]
Started getting an error today and it looks like it is related to importing a private file from the React codebase.

Error I'm seeing:

```
ERROR in ./~/react-css-transition-replace/~/react/lib/ReactAddonsDOMDependencies.js
Module not found: Error: Cannot resolve module 'react-dom/lib/ReactDOM' in PROJECT/node_modules/react-css-transition-replace/node_modules/react/lib
 @ ./~/react-css-transition-replace/~/react/lib/ReactAddonsDOMDependencies.js 13:15-48

ERROR in ./~/react-css-transition-replace/~/react/lib/ReactAddonsDOMDependencies.js
Module not found: Error: Cannot resolve module 'react-dom/lib/ReactInstanceMap' in PROJECT/node_modules/react-css-transition-replace/node_modules/react/lib
 @ ./~/react-css-transition-replace/~/react/lib/ReactAddonsDOMDependencies.js 14:23-64

ERROR in ./~/react-css-transition-replace/~/react/lib/ReactTransitionEvents.js
Module not found: Error: Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName' in PROJECT/node_modules/react-css-transition-replace/node_modules/react/lib
 @ ./~/react-css-transition-replace/~/react/lib/ReactTransitionEvents.js 15:33-84
```

I'm using 15.3.2 specifically in the project but webpack build ends up trying to use the newer version of React for the production build.

**Comment by marnusw** [comment]
Thanks for reporting this, I'll take a look.

**Comment by seriallos** [comment]
This may specifically be related to NPM 2.x which is what my project is using at the moment.  It appears NPM 3.x may not be encountering this issue.  Still trying to track down specific.

**Comment by seriallos** [comment]
For the moment, we made a private fork and pinned all the react dependencies to `~15.3.0` to get things working again.  Without pinning to 15.3, NPM 2 ends up with two copies of React which unleashes all kinds of problems.

**Comment by marnusw** [comment]
I'm running the demo on React 15.4.2 via NPM 3 and all seems to work fine. I will close this for now as I think most projects will be using NPM 3 these days.
