### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by vincentaudebert** [marnusw/react-css-transition-replace#33]
Hi,

I'm currently experiencing some issues on my project when I have two ReactCSSTransitionReplace in my component. Only the second one is actually working for some unknown reasons...
But I went on the demo page and it seems that none of the examples are working.
Is it correct?

Cheers.

**Comment by marnusw** [comment]
@vincentaudebert all the examples on http://marnusw.github.io/react-css-transition-replace/ seem to work for me. I'm using Chrome, which browser did you test with? And are they still not working for you?

**Comment by vincentaudebert** [comment]
@marnusw it seems to works now. Weird. I'm on Firefox.

Cheers.
