### ISSUE TITLE
Can I use this with react-router v4?

### ISSUE THREAD

**Issue by mreishus** [marnusw/react-css-transition-replace#46]
I'd like to be able to do something like this:

```
        <Route render={({ location }) => (
            <div>
                    <ReactCSSTransitionReplace
                        transitionName="cross-fade"
                        transitionEnterTimeout={1000}
                        transitionLeaveTimeout={1000}
                    >
                        <Route key={location.key + "one"} exact path="/" component={HomePage}/>
                        <Route key={location.key + "two"}  path="/two" component={SomeOtherComponent}/>
                        <Route key={location.key + "three"}  path="/three" component={YetAnotherComponent}/>
                    </ReactCSSTransitionReplace>
            </div>
        )}/>
```

However, I can't because RCTReplace expects an only child.  Is there any sort of workaround I can do?

**Comment by mreishus** [comment]
BTW - the other Routes render null in this specific case (there will be one active, and two nulls, always), however in the general case other code could set up routes that have multiple tags rendering.

**Comment by marnusw** [comment]
I think using the React Router [`<Switch>`](https://reacttraining.com/react-router/web/api/Switch) might be the answer. I just browsed through their docs and found this, I haven't actually tested it so I'd be interested to know whether it works for you. In your case it would mean:

```javascript
<Route render={({ location }) => (
  <div>
    <ReactCSSTransitionReplace {...}>
      <Switch>
        <Route key={location.key + "one"} exact path="/" component={HomePage}/>
        <Route key={location.key + "two"}  path="/two" component={SomeOtherComponent}/>
        <Route key={location.key + "three"}  path="/three" component={YetAnotherComponent}/>
      </Switch>
    </ReactCSSTransitionReplace>
  </div>
)}/>
```

If that doesn't work RCTReplace might be modified to strip out nulls from its children before requiring a single remaining child. This might be a neat addition to the component either way, but if the above solution works that would be great.

**Comment by phyrog** [comment]
I'm trying to do the same thing, but your proposed solution does not work, as RCTR detects the `Switch` as its child, not the component the route renders. I also tried wrapping the routes and also the components, but none of them work.

It seems like what we would have to do is:

```
<Switch>
  <ReactCSSTransitionReplace {...}>
    <Route {...}/>
    <Route {...}/>
  </ReactCSSTransitionReplace>
</Switch>
```

But this doesn't work either, since 1. `ReactCSSTransitionReplace` can only have one child and 2. `Switch` expects the immediate children to be routes (or at least have the props the route should have).

The only solution that I see at the moment, which doesn't involve changing both libraries, would be to add a special case for when the child is a `Switch`.

**Comment by uxlayouts** [comment]
I have the same question with RR4 React Router Config:

import React from 'react';
import { renderRoutes } from 'react-router-config';
import ReactCSSTransitionReplace from 'react-css-transition-replace';
import { shape } from 'prop-types';

const Base = ({route, location}, {router}) => (
  <div className="App">
    <ReactCSSTransitionReplace
      transitionName="cross-fade"
      transitionEnterTimeout={1000}
      transitionLeaveTimeout={1000}
    >
      {renderRoutes(route.routes)}
    </ReactCSSTransitionReplace>
  </div>
);

Base.propTypes = {
  location: shape({}),
};

export default Base;

**Comment by phyrog** [comment]
@marnusw your example is almost working. You need to pass the location to the `Switch` and set a key on the switch that changes when the location changes (e.g. `location.pathname`).

However, there are problems when no route matches, as `Switch` will render null, but the child of `ReactCSSTransitionReplace` is not null:

```
Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at ReactCSSTransitionReplace.componentWillReceiveProps (ReactCSSTransitionReplace.js:167)
...
```

So I guess to handle this, you would need to check if the child renders something instead of just checking if there is a child.

**Comment by marnusw** [comment]
Thanks @phyrog! If will be good if that works and then it should definitely be added to the docs. I'll see if I can address that error over the weekend, and if someone beats me to it with a PR that will also work.

**Comment by romanlex** [comment]
Hello. Your examples not work with react-router-config and subchilds routes.
 I think what trouble in Switch render.
```javascript
const routes = [
	{
		component: LandingLayout,
		path: '/',
		exact: true,
		routes: [
			{
				path: '/',
				exact: true,
				name: 'Landing',
				component: Landing,
			},
		]
	},
	{
		component: AuthLayout,
		routes: [
			{
				path: '/login',
				exact: true,
				key: 'Login',
				component: Login,
			},
			{
				path: '/recover',
				key: 'Recover',
				component: Recover,
				routes: [
					{
						path: '/recover/:code',
						name: 'RecoverProcess',
						component: RecoverProcess
					}
				]
			},
		]
	},
]
```
In AuthLayout ReactCSSTransitionReplace not work((
```javascript
<ReactCSSTransitionReplace
						component="div"
						transitionName="cross-fade"
						transitionEnterTimeout={1000}
						transitionLeaveTimeout={1000}>
						{renderRoutes(route.routes)}
					</ReactCSSTransitionReplace>
```
**renderRoutes** method render Switch without keys. How yout think its possible fix it?

**Comment by marnusw** [comment]
Version 3 has been published and the docs include a React-Router 4 example.
