### ISSUE TITLE
Problem with overlaying elements

### ISSUE THREAD

**Issue by phyrog** [marnusw/react-css-transition-replace#52]
With version 3.0 we're having problems with elements that are overlaying the transitioning elements: The transitioning element is displayed above a pop up, instead of underneath it as in 2.2.1.

Specifically this emitted HTML causes trouble:

```html
<div style="position: relative; overflow: hidden;">
  <span style="position: relative;">
    ...
  </span>
</div>
```

Removing the `style` attributes on both elements makes it work again (tested on Chrome 61 and Firefox 55), but I'm guessing this is no option.

This can be seen e.g. here (excuse the certificate error): https://tb.iks.cs.ovgu.de/
After signing in with the default login data, clicking the gravatar in the top bar reveals a dropdown, but the links are not accessible as the greeter, which uses `react-css-transition-replace` (the white text on black), is overlaying the elements.

Also: we found no way to solve this using `z-index`.

**Comment by marnusw** [comment]
This is interesting. Thank you for providing the test case. I can't recall exactly what's been changed that would cause these kinds of problems, as I recall the render method didn't change too much, but I'll investigate and get back to you.

**Comment by marnusw** [comment]
From a quick look at the diff I think it might have to do with relative vs absolute positioning of the elements. Will come back with more.

**Comment by marnusw** [comment]
This will likely be fixed in `3.0.1`. Please give it a try and if so we can close this.

**Comment by phyrog** [comment]
Will try tomorrow and report back. Thanks for looking into this!

**Comment by phyrog** [comment]
Seems to be fixed, thanks!
