### ISSUE TITLE
Is it working at all?

### ISSUE THREAD

**Issue by PainKKKiller** [marnusw/react-css-transition-replace#56]
I npm installed this lib, tried to use according to docs, and got this error:
`./~/react-css-transition-replace/lib/ReactCSSTransitionReplaceChild.js
Module not found: Error: Can't resolve 'react-transition-group/CSSTransitionGroupChild' in 'C:\Users\PainKiller\Desktop\project\node_modules\react-css-transition-replace\lib'`

**Comment by PainKKKiller** [comment]
Have no idea what's wrong. I have installed react-transition-group in my node_modules folder, and there is file CSSTransitionGroupChild.js

**Comment by gormonn** [comment]
This error occurs as a result of a combination of factors:
1. this package supports the outdated version of "react-transition-group" <в2
2. Your project has a "react-transition-group"> v1

**Comment by gormonn** [comment]
https://github.com/reactjs/react-transition-group/blob/7378b6a330ac3885c1e006f9c184ca688e4d8746/Migration.md

**Comment by marnusw** [comment]
Thanks for tracking down the issue @gormonn. I will happily upgrade the dependency to the latest of `react-transition-group`, or make this lib independent of it if that will be more practical. I'll make time when I can, unless someone is willing to submit a PR for that in the meantime.

**Comment by marnusw** [comment]
Version `3.0.3` does not depend on `react-transition-group`.
