### ISSUE TITLE
Transition breaks when run in a backgrounded tab in Chrome

### ISSUE THREAD

**Issue by jaeschliman** [marnusw/react-css-transition-replace#58]
This appears to be due to the use of requestAnimationFrame.

**Comment by mooncakelmn** [comment]
The version `3.0.3` does have such an issue, because it is using the `requestAnimationFrame`, which would stop if the tab is inactive in Chrome. 

See https://github.com/marnusw/react-css-transition-replace/blob/v3.0.3/src/ReactCSSTransitionReplace.jsx#L186
