### ISSUE TITLE
Height will sometimes get stuck at 0 when transitions are interleaved

### ISSUE THREAD

**Issue by fixpunkt** [marnusw/react-css-transition-replace#6]
When switching children really fast (e.g. triggered by a click event), the `height` of the wrapper element will sometimes get stuck at `0px`. I can reproduce this on the samples page:

http://marnusw.github.io/react-css-transition-replace/

Just click the one of the demos as fast as you can for about a minute (I've found the fade out / fade in example to show the bug most consistently). At some point, the content will disappear when I do this.

I've done some debugging and traced the problem to lines 98-102: 

    // Enqueue setting the next height to trigger the height transition.
    this.timeout = setTimeout(() => {
        this.setState({height: this.state.nextChild ? ReactDOM.findDOMNode(this.refs.next).offsetHeight : 0});
        this.timeout = null;
    }, TICK);

Changing it like this will fix the problem, but cause occasional glitches which I'm not sure how to fix:

    this.timeout = setTimeout(() => {
        const nextNode = ReactDOM.findDOMNode(this.refs.next);
        if (nextNode) {
            this.setState({height: nextChild ? nextNode.offsetHeight : 0});
        }
        this.timeout = null;
    }, TICK);

I guess this is related to http://github.com/marnusw/react-css-transition-replace/issues/4.

**Comment by marnusw** [comment]
Fixed in `v1.3.0`. See the comment in #10.
