### ISSUE TITLE
Child ref function called again with CSSTransitionGroupChild

### ISSUE THREAD

**Issue by fdev** [marnusw/react-css-transition-replace#61]
**Current behavior**
The ref function given to the child component is called with both the child component refence and the CSSTransitionGroupChild component.

**Expected behavior**
The ref function should on be called with the child component.

**Steps to reproduce**
See the example and console output on https://codesandbox.io/s/5v2nm9zo0l?expanddevtools=1

**References**
Related issue in `react-transition-group` can be found at https://github.com/reactjs/react-transition-group/issues/29 (merged fix in https://github.com/reactjs/react-transition-group/pull/39)

**Comment by marnusw** [comment]
Thank you for reporting this and for the reference to the merged fix. I will take a look.

**Comment by marnusw** [comment]
I'm sorry it took months to get round to this. I've published `4.0.2-beta.0` with a fix. Would you be able to confirm that everything now works as expected? I don't have a real use case for it so it's hard to be definitive in saying that it works.

**Comment by fdev** [comment]
I have [forked the sandbox example](https://codesandbox.io/s/tgdyy?expanddevtools=1) to use version `4.0.2-beta.0` and the issue seems to have been fixed, thanks!
