### ISSUE TITLE
Remove deprecated componentWillMount and componentWillReceiveProps

### ISSUE THREAD

**Issue by danielhusar** [marnusw/react-css-transition-replace#63]
This library provides warnings in strict more:

> componentWillMount: Please update the following components to use componentDidMount instead: CSSTransitionGroupChild, ReactCSSTransitionReplace

> componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: ReactCSSTransitionReplace

**Comment by marnusw** [comment]
@danielhusar I'm finding it hard to make time for this repo right now. Do you know whether using `UNSAFE_componentWillMount` and `UNSAFE_componentWillReceiveProps` also warn in strict mode? If not and you could submit a PR with the change I will merge and release that. I'll reengineer the component to work without those methods when I can find the time.

**Comment by marnusw** [comment]
In React 16.9 use of the old components trigger a dev warning. Both `UNSAFE_componentWillMount` and `UNSAFE_componentWillReceiveProps` will continue to work in React 16.x and 17, so it is a viable temporary solution. I will update this asap and if someone beats me to it with a contribution that would be welcome.

**Comment by danielhusar** [comment]
Looks like this has been fixed in master?
Any chance you can release new version?

**Comment by marnusw** [comment]
Fixed in `4.0.0`.

**Comment by danielhusar** [comment]
Awesome, thanks!
