### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by martinpesout** [marnusw/react-css-transition-replace#7]
I've found that it's also possible to use prop `transitionAppear={true}` to animate element on initial mount. It would be nice to update `README.md` and inform about this possibility.

Thanks for your library. You did a good job.

**Comment by marnusw** [comment]
Thanks for pointing this out. I'll add it to the docs when I release the next version.

**Comment by marnusw** [comment]
Resolved in `v1.1.1`.
