### ISSUE TITLE
React.createFactory is deprecated

### ISSUE THREAD

**Issue by sluukkonen** [marnusw/react-css-transition-replace#70]
`React.createFactory` ([used here](https://github.com/marnusw/react-css-transition-replace/blob/master/packages/react-css-transition-replace/src/ReactCSSTransitionReplace.js#L10)) has been [deprecated](https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#deprecating-reactcreatefactory) in React 16.13.0.

**Comment by Isarstyle** [comment]
+1

**Comment by marnusw** [comment]
Solved in `v4.0.3`
