### ISSUE TITLE
Remove deprecated findDOMNode? (like react-transition-group just did)

### ISSUE THREAD

**Issue by justingrant** [marnusw/react-css-transition-replace#71]
react-css-transition-replace shows warnings in Strict Mode, complaining about a deprecated API [findDOMNode](https://reactjs.org/docs/react-dom.html#finddomnode). Here's an example warning that shows in the console: 

![image](https://user-images.githubusercontent.com/277214/81374343-e42e3280-90b3-11ea-9501-d3d84fc30d54.png)

react-transition-group used to have the same problem, but as of react-transition-group [4.4.0](https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0) this API usage was removed and replaced with a ref-based solution.

Can react-css-transition-replace do something similar too?

**Comment by marnusw** [comment]
I see it's been a while since this was opened. I support this and will either do it in due course or accept a PR for it. I will be happy with a complete removal of `findDOMNode`, and then there can be a major version update for this change.

**Comment by robertwubs** [comment]
It would be awesome if this could be implemented. This components works amazingly, but this error is indeed quite jarring (let alone not really future-proof).

**Comment by marnusw** [comment]
Thanks. Please submit a PR if you need this urgently. Since react-transition-group offers a template implementation it should be pretty straightforward.

**Comment by Dagur** [comment]
PR created https://github.com/marnusw/react-css-transition-replace/pull/100

**Comment by santosch** [comment]
Hello @marnusw,
would you mind merging this PR and releasing a new version together with the other React 18 related changes?
This would be great! Thanks a lot!

**Comment by marnusw** [comment]
Thanks @Dagur and for the note @santosch. I must have missed the PR when it was first created. Sorry about the wait. I'll get to this in the next few days.

**Comment by marnusw** [comment]
Released in [5.0.0-beta.0](https://www.npmjs.com/package/react-css-transition-replace/v/5.0.0-beta.0) via #101
