### ISSUE TITLE
API compatibility with ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by marian-cojoc-ro** [marnusw/react-css-transition-replace#9]
You require `transitionName` property  to be a string, this is limiting in some cases and is not compatible with ReactCSSTransitionGroup.

https://github.com/marnusw/react-css-transition-replace/blob/master/src/ReactCSSTransitionReplace.jsx#L44

Thanks

**Comment by marnusw** [comment]
Thanks for pointing this out @marian-cojoc-ro. I've been struggling to get round to this lib over the last few weeks. I'm hoping to get to it relatively soon, but if you want to file a PR in the mean time please feel free!

**Comment by marnusw** [comment]
Resolved in `v1.1.1`.
